"""The committed WASM must be what `wasm/bb84/src/lib.rs` compiles to.

`src/lib/sim/generated/bb84KernelWasm.ts` is a build product held in git, so
`npm ci && vite build` works without Docker or a Rust toolchain -- neither of
which CI's frontend job has. The cost of committing a build product is that it
can drift from its source, and nothing would say so: the parity test in
`wasmAgreesWithWorker.test.ts` checks the COMMITTED bytes against the worker,
so an edit to lib.rs that was never rebuilt leaves that test passing on the old
module.

This rebuilds and compares. It needs Docker, so it skips where Docker is
absent -- which is honest rather than inert: the frontend job cannot run it,
and saying so beats pretending. The `images` job has Docker and is where it
bites.
"""
from __future__ import annotations

import base64
import pathlib
import re
import shutil
import subprocess

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
CRATE = ROOT / "services" / "webui-frontend" / "wasm" / "bb84"
GENERATED = (ROOT / "services" / "webui-frontend" / "src" / "lib" / "sim"
             / "generated" / "bb84KernelWasm.ts")
IMAGE = "rust:1.88-alpine"


def _committed() -> bytes:
    m = re.search(r'BB84_KERNEL_WASM_B64 =\s*\n\s*"([A-Za-z0-9+/=]+)"',
                  GENERATED.read_text(encoding="utf-8"))
    assert m, "the generated module no longer carries a base64 payload"
    return base64.b64decode(m.group(1))


def test_the_generated_module_is_present_and_declares_its_size():
    txt = GENERATED.read_text(encoding="utf-8")
    assert "GENERATED by" in txt, "the do-not-edit banner is gone"
    m = re.search(r"BB84_KERNEL_WASM_BYTES = (\d+)", txt)
    assert m, "the byte count is not exported"
    assert int(m.group(1)) == len(_committed()), (
        "the declared size and the payload disagree, so one of them was edited "
        "by hand instead of regenerated")


def test_the_payload_is_a_wasm_module():
    assert _committed()[:4] == b"\x00asm", "not a WebAssembly binary"


def test_the_bundle_cost_argument_still_holds():
    """docs/roadmap.md rejected WASM on size; 907 bytes is the rebuttal."""
    n = len(_committed())
    assert n < 2048, (
        f"the kernel is now {n} bytes. The roadmap's objection was bundle "
        f"cost and the answer was under a kilobyte; past a couple of KB that "
        f"argument needs re-making rather than assuming.")


@pytest.mark.skipif(shutil.which("docker") is None,
                    reason="docker absent; the images job runs this for real")
def test_rebuilding_reproduces_the_committed_bytes():
    """The real check: source in, identical artefact out."""
    r = subprocess.run(
        ["docker", "run", "--rm", "-v", f"{CRATE}:/w", "-w", "/w", IMAGE, "sh", "-c",
         "rustup target add wasm32-unknown-unknown >/dev/null 2>&1 && "
         "cargo build --release --target wasm32-unknown-unknown >/dev/null 2>&1 && "
         "cat target/wasm32-unknown-unknown/release/bb84_kernel.wasm"],
        capture_output=True, timeout=900, check=False)
    assert r.returncode == 0, f"rebuild failed: {r.stderr.decode()[:400]}"
    assert r.stdout, "rebuild produced no bytes"
    assert r.stdout == _committed(), (
        "the committed WASM differs from what wasm/bb84 compiles to. Run "
        "`bash services/webui-frontend/wasm/build.sh` and commit the result -- "
        "the parity test checks the COMMITTED module, so a stale artefact "
        "passes it while shipping the old kernel.")
