#!/usr/bin/env bash
# Build the BB84 WASM kernel and emit it as an inlined TypeScript module.
#
# Containerised on purpose. The host may have cargo without the wasm32 std (the
# packaged Rust on RHEL does, and there is no rustup to add it), so building
# here would depend on which machine ran it. A pinned image makes the artefact a
# function of the source only.
#
# The output is committed. That is deliberate: `npm ci && vite build` must work
# without Docker or a Rust toolchain, and CI's frontend job has neither. The
# guard in src/lib/sim/wasmArtefactIsCurrent.test.ts rebuilds and compares, so a
# stale commit is a red test rather than a silent drift.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/../src/lib/sim/generated/bb84KernelWasm.ts"
IMAGE="rust:1.88-alpine"

docker run --rm -v "$HERE/bb84:/w" -w /w "$IMAGE" sh -c '
  rustup target add wasm32-unknown-unknown >/dev/null 2>&1
  cargo build --release --target wasm32-unknown-unknown >/dev/null
  cat target/wasm32-unknown-unknown/release/bb84_kernel.wasm
' > "$HERE/bb84_kernel.wasm"

BYTES=$(wc -c < "$HERE/bb84_kernel.wasm")
B64=$(base64 -w0 < "$HERE/bb84_kernel.wasm")

mkdir -p "$(dirname "$OUT")"
{
  echo "// GENERATED by services/webui-frontend/wasm/build.sh -- do not edit."
  echo "//"
  echo "// Source: wasm/bb84/src/lib.rs, built with $IMAGE for"
  echo "// wasm32-unknown-unknown, release profile (opt-level=z, lto, strip)."
  echo "//"
  echo "// $BYTES bytes. Inlined as base64 rather than shipped as a separate"
  echo "// asset: a second network round trip would undercut the point of a page"
  echo "// that computes client-side, and the base64 overhead at this size is"
  echo "// about 300 bytes."
  echo "export const BB84_KERNEL_WASM_BYTES = $BYTES;"
  echo "export const BB84_KERNEL_WASM_B64 ="
  echo "  \"$B64\";"
  echo ""
  echo "/** Decode to the bytes WebAssembly.instantiate wants. */"
  echo "export function bb84KernelWasm(): Uint8Array {"
  echo "  const bin = atob(BB84_KERNEL_WASM_B64);"
  echo "  const out = new Uint8Array(bin.length);"
  echo "  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);"
  echo "  return out;"
  echo "}"
} > "$OUT"

rm -f "$HERE/bb84_kernel.wasm"
echo "wrote $OUT ($BYTES bytes of wasm)"
